version: '3'
services:
  movieinfo:
    image: "keremk/movieinfo:v0.3"
    ports:
    - "3030:3030"
    environment:
    - FAIL_PERCENT=0.2
    - MAX_ALLOWED=5
  moviesearch:
    image: "keremk/moviesearch:v0.4"
    ports:
    - "3040:3030"
    environment:
    - FAIL_PERCENT=0.1
  artistinfo:
    image: "keremk/artistinfo:v0.3"
    ports:
    - "3050:3030"
    environment:
    - FAIL_PERCENT=0.5
    - MAX_ALLOWED=5
  ratingsstream:
    image: "keremk/ratingsstream:v0.3"
    ports:
    - "3020:3000"